### ISSUE TITLE
ReArch vs Signals

### ISSUE THREAD

**Issue by jtkeyva** [GregoryConrad/rearch-dart#137]
How does this compare to https://pub.dev/packages/signals ? 
Why would I use one over the other?
Thanks

**Comment by GregoryConrad** [comment]
Could’ve sworn I’ve answered this before somewhere, but I couldn’t find it, so here’s a brief list of the differences.

signals only constitute a subset of ReArch’s functionality. If you:
- got rid of containers, instead opting for a single global/static instance
- removed side effect composition
- removed many of the builtin effects

You’d finally arrive at signals. In fact, I’m fairly sure you could entirely implement signals above ReArch because it does only constitute a subset of ReArch’s features.

**Comment by jtkeyva** [comment]
thank you. i may make the leap from bloc but this is a big move. so essentially signals is a feature of ReArch?  i am easily able to wrap my head around signals. maybe it's the docs or naming convention?

signals has a lot of momentum, perhaps "Why not Signals" would be a good addition to your docs

**Comment by GregoryConrad** [comment]
> so essentially signals is a feature of ReArch? 

More or less, yup. AFAIK all the specific types of signals have a corresponding effect that you can use in ReArch. Example: use.state for a regular signal, use.future for a future signal, etc. etc.

> perhaps "Why not Signals" would be a good addition to your docs

agreed, thought I had added it before but I guess I haven’t

**Comment by jtkeyva** [comment]
thank you sir :)
