### ISSUE TITLE
Please correct your statement on why not get_it :-)

### ISSUE THREAD

**Issue by escamoteur** [GregoryConrad/rearch-dart#142]
with watch_it there is a reactive extenstion to get_it for quite a while now.

**Comment by escamoteur** [comment]
you missed, that for some years there were the get_it_mixin around and since last August there is the watch_it package that is the companion package for get_it.

**Comment by GregoryConrad** [comment]
I'm aware of watch_it, but watch_it only provides Widget/UI reactivity, not inter-state reactivity. I.e., in the overused count example, I couldn't have a `Count` class registered with get_it, and then have a `CountPlusOne` class who's state watches that of `Count` (without Streams, ValueNotifiers, etc. which have their own problems that prevent correct composition across states).

**Comment by escamoteur** [comment]
What is the problem using a Stream or Valuelistenable? why mixing state management with business logic?

**Comment by GregoryConrad** [comment]
In addition to the items mentioned [here](https://github.com/gregoryconrad/rearch-dart/?tab=readme-ov-file#why-not-rx-and-streams) (under "why not rx and streams"), there is also a big issue w.r.t. composition, see [page 14 here](https://digitalwpi.wpi.edu/pdfviewer/41687p008).

> why mixing state management with business logic?

Business logic can be stateful--what happens when you want to fetch the current signed in user's posts in a social media application? In this situation, and virtually every other regarding how to build some piece of software, it is easiest to model the problem exactly as described via its underlying data and that data's requirements:
- have a state of current signed in user
- have a state that uses the current signed in user to grab the posts of that current user

Now if you want to discuss local/ephemeral state, you may use an individual ValueNotifier for just a singular state. But that also isn't as easy to set up as a one line:
```dart
final (state, setState) = use.state(); // or useState(); if you are using hooks
```

One main difference ReArch brings to the table here is that you may use this same "effects" API (`use.state` above, but there are dozens of others) to write both widgets and your global state/business logic to create cohesion across your app.

**Comment by escamoteur** [comment]
hmm, thanks for your Thesis, will check it out
>have a state that uses the current signed in user to grab the posts of that current user
why whould a state grab any data? I'm not sure that this makes it easier to understand what is going on in your app.

I'm working for over a year on a fairly big social media app and we didn't face any of your listed problems. However we use flutter_commands in addition to watch_it as the reactive link for our business logic.

**Comment by GregoryConrad** [comment]
> why whould a state grab any data? I'm not sure that this makes it easier to understand what is going on in your app.

Because it enables declarative code, which in turn enables automatically reactive code. This particular social app example could look something like:

```dart
/// Represents the current signed in user.
User currentUserCapsule(CapsuleHandle use) => throw 'impl hidden';

/// Fetches a user's posts via REST API.
Future<List<Post>> Function(User user) fetchUserPostsAction(CapsuleHandle use) => throw 'impl hidden';

/// Represents the posts of the current signed in user.
Future<List<Post>> currentUserPostsCapsule(CapsuleHandle use) {
  final user = use(currentUserCapsule);
  return use(fetchUserPostsAction)(user);
}
```

The `currentUserPostsCapsule` is a simple composition of the two other pieces of state/logic, all while remaining highly testable and completely satisfying many well known design principles/patterns like SOLID (for free due to the nature of ReArch's design).

There are other ways to achieve this exact kind of behavior, but I'd argue they aren't as simple as just modeling your app in terms of data flow (which, at the end of the day, is all any application is--just one big data in and out machine).

> However we use flutter_commands in addition to watch_it as the reactive link for our business logic.

Had to look up flutter_command since I haven't heard of it before--based on what I'm reading you might really like ReArch haha

> A Command is an object that wraps a function that can be executed by calling the command, therefore decoupling your UI from the wrapped function.

In ReArch, you don't need any layers of indirection like this since capsules provide dependency inversion over any functions they contain too. In our example above, all a widget has to do is `use(fetchUserPostsAction)` and they get their own copy of the function that they can call with any user that might be local/ephemeral state.

**Comment by escamoteur** [comment]
Definitely will look into it.
How is your view on the currently hyped Signals packages?
Am 15. Apr. 2024, 17:25 +0200 schrieb Gregory Conrad ***@***.***>:

**Comment by GregoryConrad** [comment]
> How is your view on the currently hyped Signals packages?

Funny you mention that; I actually just added a section to the README on that after the question arose a day or two ago in #137.

https://github.com/GregoryConrad/rearch-dart#why-not-signals

Copy pasted for easy reference:

#### Why not Signals?

Signals only constitute a subset of ReArch's functionality.
If you took ReArch and removed:
- Containers, instead opting for global singletons
- The builtin side effects, instead opting for only a few hard-coded types of signals
- [Side effect composition](https://blog.gsconrad.com/2023/12/22/the-problem-with-state-management.html)
- The ability for capsules to define their own API for interactions, instead allowing only `.value`
  - To explain this a bit more: what if you want custom state validation logic alongside your state?

Then you'd arrive at ReArch.

So, if you like Signals, you'll likely love ReArch,
because you'll get all of the benefits of Signals
but with many more features (mostly due to ReArch's side effects model).
The only main difference is in the API,
but that is easy enough to adjust to--signals and capsules tend to map one-to-one.

**Comment by escamoteur** [comment]
OK, I spend some time trying to understand the whole concept and honestly I find the code with capsules etc very hard to read. I'm pretty sure when writing it it might be different but compared with a combination of watch_it with flutter_commands it feels way harder to understand what is going on in the code. 
Maybe coming from Rust that might be different, but I'm not sure that it makes live for Flutter developers really easier.
I think I can understand the motivation behind it but IMHO using proper OO design helps a lot to document what your app is doing even if it will take a lot more code to write.
Curious how much traction you will get with that package.

**Comment by busslina** [comment]
> I find the code with capsules etc very hard to read.
I felt the same (coming from Riverpod), but after a time adapting mentally it's just pretty. A part of all the benefits that his creator mention, personally, from my experience I would highlight the speed of writing/refactoring code it brings. And once you adapt to it I would say it's easier (I only know Riverpod).

**Comment by busslina** [comment]
Example:

```dart
Future<Ret<String, dynamic>> authTokenCapsule(CapsuleHandle use) async {
  // TODO: check if it is close to expire

  // TODO: schedule expire handler and delete it

  final config = use(appConfigCapsule);
  final configSetter = use(appConfigSetterCapsule);

  final authToken = config.authToken;

  if (authToken != null) return Ret.success(value: authToken);

  final username = ConsoleUtilsV2.readValue('API username: ');
  final password = ConsoleUtilsV2.readPassword('API password: ');

  final res =
      (await use(backendApiLoginCapsule).login(username, password)).logFailed();

  if (res.failed) throw (res.errMessage!);

  final newAuthToken = res.value!;

  final newConfig = config.copyWith(authToken: newAuthToken);

  newConfig.saveToFile();

  configSetter(newConfig);

  return Ret.success(value: newAuthToken);
}

Dio _authHttpClientCapsule(CapsuleHandle use) {
  return Dio(
    BaseOptions(
      validateStatus: (status) => switch (status) {
        200 => true,
        401 => true,
        _ => false,
      },
    ),
  );
}

BackendApiLoginController backendApiLoginCapsule(CapsuleHandle use) {
  final httpClient = use(_authHttpClientCapsule);

  return BackendApiLoginController(login: (username, password) async {
    final res = await handleResponse(httpClient.post(loginApiUrl, data: {
      'username': username,
      'password': password,
    }));

    if (res.success) {
      return Ret.success(value: res.response.data as String);
    }

    return Ret.error('Status code: ${res.statusCode}');
  });
}

class BackendApiLoginController {
  final Future<Ret<String, dynamic>> Function(String, String) login;

  BackendApiLoginController({
    required this.login,
  });
}

```

**Comment by escamoteur** [comment]
I guess that is my main pain point. Dart isn't a first class functional language which leads to not optimal syntax if you try to use it purely functional. f# is an amazing example how good FP code can look like.
I'm an OOP guy and still think its a pretty good paradigm especially for full applications. 
On the server I think FP is a better fit.

**Comment by GregoryConrad** [comment]
Fair enough. If you like OOP and want to stick to that exclusively in your apps, then ReArch isn’t for you. I used to love OOP some years ago, but got increasingly frustrated with it as time went on. I could never make things exactly like I envisioned them.

as far as the functional aspects, I tried to make ReArch not too reliant on anything FP-specific to the point where it wouldn’t fit in Dart, and I’d say ReArch achieves that. There are things like AsyncValue, but that’s no sin in my book since Flutter itself has an AsyncSnapshot and Riverpod also has a similar AsyncValue.

I do hear what you’re saying about using functional approaches in an OOP language, but I don’t think ReArch goes too far down that rabbit hole unlike some other Dart/JS libraries I’ve seen.
