### ISSUE TITLE
Change `setter` of `lazyStateGetterSetter` to return `bool` (on whether state changes)

### ISSUE THREAD

**Issue by busslina** [GregoryConrad/rearch-dart#43]
Current is:
```dart
void setter(T newState) {
        if (newState == state) return;
        state = newState;
        api.rebuild();
      }
```

Proposed change:
```dart
bool setter(T newState) {
        if (newState == state) return false;
        state = newState;
        api.rebuild();
        return true;
      }
```

**Comment by GregoryConrad** [comment]
Can you please provide a use case for this change? Often state setters should be void to force the use of reactivity.

**Comment by busslina** [comment]
I have this method:

```dart
Future<bool> changeValue(
    FutureOr<T?> newValueFutureOr, {
    required ConnectionKey? callerConnectionKey,
    bool byPassEditable = false,
  }) async {
    if (!_isEditable && !byPassEditable) {
      warning(
          '_ResourceValueWrapper<$T>.changeValue() -- Trying to edit a not editable resource -- $_value -- $newValueFutureOr');
      return false;
    }

    T? newValue;

    try {
      newValue = await newValueFutureOr;
    } on UpdateErrorException catch (e) {
      warning('_ResourceValueWrapper<$T, $MappedValue>.changeValue() -- $e');

      if (callerConnectionKey != null) {
        _notifyUpdateErrorToCaller(e, callerConnectionKey: callerConnectionKey);
      }

      return false;
    } catch (e) {
      warning(
          '_ResourceValueWrapper<$T, $MappedValue>.changeValue() -- Unexpected error: $e');
      return false;
    }

    if (_value == newValue) {
      return false;
    }

    final newVersionedValue = _VersionedValue(newValue, _version + 1);

    _setValue(newVersionedValue);

    // Notifying listeners
    _listeners.notify(
      _mapValue(newVersionedValue.value),
      newVersionedValue.version,
    );

    return true;
  }
```

You can see this:
```dart
if (_value == newValue) {
      return false;
    }
```

With the proposal change I could remove a pair of lines there.

(*) Notify listeners is not breaking reactivity. They are external listeners (websocket connections)

**Comment by GregoryConrad** [comment]
I think the issue is that I'd suggest:
```dart
    // Notifying listeners
    _listeners.notify(
      _mapValue(newVersionedValue.value),
      newVersionedValue.version,
    );
```
to be in its own dependent listener capsule, and thus everything stays reactive.

If this is a part of your resource side effect from previous discussions we've had, then that is an adequate exception to the normal rule just to reduce the amount of boilerplate required (even though it does break reactivity a little bit). And since that is largely an exception to the norm because of the desire to not have as much boilerplate for listeners, I don't know if I'm inclined to do this right now. I don't want someone new to the library to come along in the future, see the setters return a bool, and then use that to handle reactivity that they probably should be doing via capsule composition.

**Comment by busslina** [comment]
Regarding the listeners/notifier I will create a discussion. I tried to do the more lighter/sophisticated way. I will show you for feedbacks.

Thanks ;)
